### ISSUE TITLE
[BUG] Schema target points to null 

### ISSUE THREAD

**Issue by lukepolo** [5stackgg/5stack-panel#23]
## Environment
- 5Stack Plugin Version: 0.0.53

```
2024-11-01 20:00:42.885 +02:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Schema target points to null. (Parameter 'pointer')
   at CounterStrikeSharp.API.Core.CBasePlayerController.get_SteamID() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CBasePlayerController.g.cs:line 119
   at FiveStack.CaptainSystem.IsCaptain(CCSPlayerController player, CsTeam team) in /mod/src/FiveStack.Services/CaptainSystem.cs:line 171
   at FiveStack.MatchManager.<>c__DisplayClass30_0.<EnforceMemberTeam>b__0() in /mod/src/FiveStack.Services/MatchManager.cs:line 450
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
2024-11-01 20:00:56.966 +02:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Schema target points to null. (Parameter 'pointer')
   at CounterStrikeSharp.API.Core.CBasePlayerController.get_SteamID() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CBasePlayerController.g.cs:line 119
   at FiveStack.CaptainSystem.IsCaptain(CCSPlayerController player, CsTeam team) in /mod/src/FiveStack.Services/CaptainSystem.cs:line 171
   at FiveStack.MatchManager.<>c__DisplayClass30_0.<EnforceMemberTeam>b__0() in /mod/src/FiveStack.Services/MatchManager.cs:line 450
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
2024-11-01 20:00:57.074 +02:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Schema target points to null. (Parameter 'pointer')
   at CounterStrikeSharp.API.Core.CBasePlayerController.get_SteamID() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CBasePlayerController.g.cs:line 119
   at FiveStack.CaptainSystem.IsCaptain(CCSPlayerController player, CsTeam team) in /mod/src/FiveStack.Services/CaptainSystem.cs:line 171
   at FiveStack.MatchManager.<>c__DisplayClass30_0.<EnforceMemberTeam>b__0() in /mod/src/FiveStack.Services/MatchManager.cs:line 450
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
   ```

**Comment by lukepolo** [comment]
something with the CaptainSystem

**Comment by lukepolo** [comment]
https://github.com/5stackgg/game-server/commit/9385d60152b6f9e58506a1a23ba7eaeb5d3e5133
