### ISSUE TITLE
[BUG]  Sessions emtpy

### ISSUE THREAD

**Issue by lukepolo** [5stackgg/5stack-panel#41]
2024-11-09T05:38:30.151303842Z
[Nest] 1 - 11/09/2024, 5:38:30 AM ERROR [WsExceptionsHandler] Cannot read properties of undefined (reading 'sessions')
2024-11-09T05:38:30.151332858Z
TypeError: Cannot read properties of undefined (reading 'sessions')
2024-11-09T05:38:30.151335718Z
at MatchLobbyService.leaveLobbyViaGame (/opt/5stack/dist/src/matches/match-lobby.service.js:205:22)
2024-11-09T05:38:30.151337229Z
at PlayerDisconnected.process (/opt/5stack/dist/src/matches/events/PlayerDisconnected.js:7:31)
2024-11-09T05:38:30.151338646Z
at MatchEventsGateway.handleMatchEvent (/opt/5stack/dist/src/matches/match-events.gateway.js:57:25)
2024-11-09T05:38:30.151340589Z
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2024-11-09T05:38:30.151342279Z
at async MatchEventsGateway. (/opt/5stack/node_modules/@nestjs/websockets/context/ws-proxy.js:12:32)
2024-11-09T05:38:30.151355022Z
at async WebSocketsController.pickResult (/opt/5stack/node_modules/@nestjs/websockets/web-sockets-controller.js:96:24)

**Comment by lukepolo** [comment]
https://github.com/5stackgg/api/commit/5985b676d033f941eea961a63bbd189b9fe00809
