### ISSUE TITLE
[BUG] Error from Logs on 2nd map of best of 3

### ISSUE THREAD

**Issue by lukepolo** [5stackgg/5stack-panel#52]
```
2024-11-12T23:39:40.257065562Z
23:39:40 [EROR] (cssharp:Core) Error invoking callback
2024-11-12T23:39:40.257098695Z
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
2024-11-12T23:39:40.257108242Z
---> System.ArgumentNullException: Schema target points to null. (Parameter 'pointer')
2024-11-12T23:39:40.257115789Z
at CounterStrikeSharp.API.Core.CBasePlayerController.get_SteamID() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CBasePlayerController.g.cs:line 119
2024-11-12T23:39:40.257127557Z
at FiveStack.CaptainSystem.IsCaptain(CCSPlayerController player, CsTeam team) in /mod/src/FiveStack.Services/CaptainSystem.cs:line 176
2024-11-12T23:39:40.257138517Z
at FiveStack.MatchManager.SendUpdatedMatchLineups() in /mod/src/FiveStack.Services/MatchManager.cs:line 554
2024-11-12T23:39:40.257145867Z
at FiveStack.MatchManager.UpdateMapStatus(eMapStatus status) in /mod/src/FiveStack.Services/MatchManager.cs:line 153
2024-11-12T23:39:40.257152211Z
at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 64
2024-11-12T23:39:40.257158503Z
at InvokeStub_Action`2.Invoke(Object, Span`1)
2024-11-12T23:39:40.257165489Z
at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2024-11-12T23:39:40.257172914Z
--- End of inner exception stack trace ---
2024-11-12T23:39:40.257178909Z
at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2024-11-12T23:39:40.257184903Z
at System.Delegate.DynamicInvokeImpl(Object[] args)
2024-11-12T23:39:40.257191340Z
at CounterStrikeSharp.API.Core.FunctionReference.b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
2024-11-12T23:39:40.257065562Z
23:39:40 [EROR] (cssharp:Core) Error invoking callback
2024-11-12T23:39:40.257098695Z
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
2024-11-12T23:39:40.257108242Z
---> System.ArgumentNullException: Schema target points to null. (Parameter 'pointer')
2024-11-12T23:39:40.257115789Z
at CounterStrikeSharp.API.Core.CBasePlayerController.get_SteamID() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CBasePlayerController.g.cs:line 119
2024-11-12T23:39:40.257127557Z
at FiveStack.CaptainSystem.IsCaptain(CCSPlayerController player, CsTeam team) in /mod/src/FiveStack.Services/CaptainSystem.cs:line 176
2024-11-12T23:39:40.257138517Z
at FiveStack.MatchManager.SendUpdatedMatchLineups() in /mod/src/FiveStack.Services/MatchManager.cs:line 554
2024-11-12T23:39:40.257145867Z
at FiveStack.MatchManager.UpdateMapStatus(eMapStatus status) in /mod/src/FiveStack.Services/MatchManager.cs:line 153
2024-11-12T23:39:40.257152211Z
at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 64
2024-11-12T23:39:40.257158503Z
at InvokeStub_Action`2.Invoke(Object, Span`1)
2024-11-12T23:39:40.257165489Z
at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2024-11-12T23:39:40.257172914Z
--- End of inner exception stack trace ---
2024-11-12T23:39:40.257178909Z
at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2024-11-12T23:39:40.257184903Z
at System.Delegate.DynamicInvokeImpl(Object[] args)
2024-11-12T23:39:40.257191340Z
at CounterStrikeSharp.API.Core.FunctionReference.b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

**Comment by lukepolo** [comment]
https://github.com/5stackgg/game-server/commit/bab67b8fa88f775d3b3d3f6b15d476063347dadc
